spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cats
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:user}
    password: ${DB_PASS:admin}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # defaults to create-drop when using h2
    hibernate:
      #   ddl-auto: create-drop
      #   ddl-auto: update
      ddl-auto: validate
